

            <!--Using Flexcontainer to wrap the nav elements if there is not enough space to diplay them inline-->
            <!--https://www.w3schools.com/css/css3_flexbox.asp-->
            <nav class="flex-container">
                <a class="homepage" href="index.php">Homepage</a> 
                <a class="homepage" href="product.php">Our Products</a>
                <a class="homepage" href="enquire.php">Product Enquire</a>
                <a class="homepage" href="about.php">About Me</a>
                <a class="homepage" href="enhancements.php">Enhancements</a>
                <a class="homepage" href="enhancements2.php">Enhancements 2</a>
                <a class="homepage" href="enhancements3.php">Enhancements 3</a>
                <a class="homepage" href="manager.php">Manager Area</a>
                <a class="homepage" href="accessability.html">Accessability Report</a>
            </nav>
          <hr/>
